spring:
  application:
    name: store2
  datasource:
    url: jdbc:mysql://localhost:3306/store2?createDatabaseIfNotExist=true
    username: root
    password: 2003
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800
stripe:
  secretKey: ${STRIPE_SECRET_KEY}

websiteUrl: http://localhost:4242